site_name: KCEO Glossary
site_url: https://ec-jrc.github.io/KCEO-Glossary/
site_author: KCEO
site_description: KCEO

nav:
    - Home: index.md
    - Glossary:
        - Introduction: introduction.md
        - Concepts: concepts.md
        - Dependency Graph: sigmajs.md
        - Topology: glossary_topology.md
        - Tags: tags.md
        - Terms:
          - Accuracy: terms/accuracy.md
          - Ancillary data: terms/ancillary_data.md
          - Anthroposphere: terms/anthroposphere.md
          - Archive: terms/archive.md
          - Area of interest: terms/area_of_interest.md
          - Atmosphere: terms/atmosphere.md
          - Auxiliary data: terms/auxiliary_data.md
          - Backup: terms/backup.md
          - Band central wavelength: terms/band_central_wavelength.md
          - Baseline: terms/baseline.md
          - Biosphere: terms/biosphere.md
          - Business continuity: terms/business_continuity.md
          - Calibration: terms/calibration.md
          - Cartographic projection: terms/cartographic_projection.md
          - Catalogue: terms/catalogue.md
          - Cell: terms/cell.md
          - Characteristic: terms/characteristic.md
          - Classification system: terms/classification_system.md
          - Classification system levels: terms/classification_system_levels.md
          - Climate projection: terms/climate_projection.md
          - Collection: terms/collection.md
          - Collection update: terms/collection_update.md
          - Collection upgrade: terms/collection_upgrade.md
          - Concepts: terms/concepts.md
          - Confidence interval: terms/confidence_interval.md
          - Contribute: terms/contribute.md
          - Copernicus Service Provider: terms/copernicus_service_provider.md
          - Coverage interval: terms/coverage_interval.md
          - Cryosphere: terms/cryosphere.md
          - Custodian: terms/custodian.md
          - Data: terms/data.md
          - Data access: terms/data_access.md
          - Data format: terms/data_format.md
          - Data licencing: terms/data_licencing.md
          - Decommissioned product: terms/decommissioned_product.md
          - Deprecated product: terms/deprecated_product.md
          - Derivative product: terms/derivative_product.md
          - Dispose: terms/dispose.md
          - Duration: terms/duration.md
          - Dwell time: terms/dwell_time.md
          - EO space data: terms/eo_space_data.md
          - Earth Observation: terms/earth_observation.md
          - Earth Observation based output: terms/earth_observation_based_output.md
          - Earth Observation product: terms/earth_observation_product.md
          - Earth Spheres: terms/earth_spheres.md
          - Entity: terms/entity.md
          - Environmental process: terms/environmental_process.md
          - Expanded uncertainty: terms/expanded_uncertainty.md
          - Feature: terms/feature.md
          - Final product version: terms/final_product_version.md
          - Forecast range: terms/forecast_range.md
          - Geocoding: terms/geocoding.md
          - Geographic coordinate reference system: terms/geographic_coordinate_reference_system.md
          - Geographic data: terms/geographic_data.md
          - Geographic grid: terms/geographic_grid.md
          - Geographic identifier: terms/geographic_identifier.md
          - Geolocating: terms/geolocating.md
          - Geolocation information: terms/geolocation_information.md
          - Geopositioning: terms/geopositioning.md
          - Georectifying: terms/georectifying.md
          - Geospatial data: terms/geospatial_data.md
          - Geosphere: terms/geosphere.md
          - Granule: terms/granule.md
          - Grid: terms/grid.md
          - Hydrosphere: terms/hydrosphere.md
          - Impact: terms/impact.md
          - In-Situ Observation: terms/in-situ_observation.md
          - Information: terms/information.md
          - Instrument data: terms/instrument_data.md
          - Introduction: terms/introduction.md
          - Laboratory observation: terms/laboratory_observation.md
          - Latency: terms/latency.md
          - Lead time: terms/lead_time.md
          - Lithosphere: terms/lithosphere.md
          - Location: terms/location.md
          - Location error: terms/location_error.md
          - Long term preservation: terms/long_term_preservation.md
          - Measurand: terms/measurand.md
          - Measurement: terms/measurement.md
          - Measurement uncertainty: terms/measurement_uncertainty.md
          - Metadata: terms/metadata.md
          - Minimum Mapping Unit: terms/minimum_mapping_unit.md
          - Minimum Mapping Width: terms/minimum_mapping_width.md
          - Model: terms/model.md
          - Near real time data: terms/near_real_time_data.md
          - Object: terms/object.md
          - Observation: terms/observation.md
          - Obsolete product or collection: terms/obsolete_product_or_collection.md
          - Outcome: terms/outcome.md
          - Path: terms/path.md
          - Period: terms/period.md
          - Period Identifier: terms/period_identifier.md
          - Phenomenon: terms/phenomenon.md
          - Place: terms/place.md
          - Policy: terms/policy.md
          - Policy cycle: terms/policy_cycle.md
          - Policy file: terms/policy_file.md
          - Policy making: terms/policy_making.md
          - Policy milestone: terms/policy_milestone.md
          - Policy objective: terms/policy_objective.md
          - Policy target: terms/policy_target.md
          - Position: terms/position.md
          - Preservation: terms/preservation.md
          - Process: terms/process.md
          - Product: terms/product.md
          - Property: terms/property.md
          - Provisional product: terms/provisional_product.md
          - Quality indicator: terms/quality_indicator.md
          - Quantity: terms/quantity.md
          - Reference: terms/reference.md
          - Remote Sensing: terms/remote_sensing.md
          - Replicability: terms/replicability.md
          - Representativeness: terms/representativeness.md
          - Reproducibility: terms/reproducibility.md
          - Sample: terms/sample.md
          - Sensor: terms/sensor.md
          - Service provider: terms/service_provider.md
          - Source data: terms/source_data.md
          - Spatial completeness: terms/spatial_completeness.md
          - Spatial consistency: terms/spatial_consistency.md
          - Spatial extent: terms/spatial_extent.md
          - Spatial reporting unit: terms/spatial_reporting_unit.md
          - Spatial resolution: terms/spatial_resolution.md
          - Spectral band: terms/spectral_band.md
          - Spectral Bandwidth: terms/spectral_bandwidth.md
          - Spectral resolution: terms/spectral_resolution.md
          - Stability: terms/stability.md
          - Standard Uncertainty: terms/standard_uncertainty.md
          - Steward: terms/steward.md
          - Temporal consistency: terms/temporal_consistency.md
          - Temporal extent: terms/temporal_extent.md
          - Temporal reporting period: terms/temporal_reporting_period.md
          - Temporal resolution: terms/temporal_resolution.md
          - Temporal revisit: terms/temporal_revisit.md
          - Thematic resolution: terms/thematic_resolution.md
          - Thematic uncertainty: terms/thematic_uncertainty.md
          - Time of day: terms/time_of_day.md
          - Time of year: terms/time_of_year.md
          - Timeliness: terms/timeliness.md
          - Traceability: terms/traceability.md
          - Trait: terms/trait.md
          - Uncertainty: terms/uncertainty.md
          - Update frequency: terms/update_frequency.md
          - User: terms/user.md
          - User Interface: terms/user_interface.md
          - Validation: terms/validation.md
          - Value: terms/value.md
          - Verification: terms/verification.md
          - Version control: terms/version_control.md
          - Vertical levels: terms/vertical_levels.md

    #- Changelog: changelog.md
    - Contribute: contribute.md
    - Blog:
      - blog/index.md
    - Contact: impressum.md

theme:
  name: material
  custom_dir: docs/theme_override_home/
  # 404 page
  static_templates:
    - 404.html
  # enable light/dark mode
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - navigation.sections
    - content.action.edit
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    
  font: false
  icon:  # from .icons path. Add to theme override for custom logo.
    logo: earth  # top left header logo
    repo: fontawesome/brands/git-alt
    edit: material/file-edit-outline
  favicon: assets/favicon.ico # browser tab logo

extra_javascript:
        - stylesheets/extra.js
        - stylesheets/tablesort.min.js
        - stylesheets/tablesort.js
extra_css:
        - stylesheets/extra.css
        - stylesheets/font-awesome-4.7.0/css/font-awesome.min.css

repo_url: https://github.com/ec-jrc/KCEO-Glossary
repo_name: ec-jrc/KCEO-Glossary
edit_uri: ./edit/main/docs

# Copyright
copyright: Copyright &copy; Knowledge Centre on Earth Observation

markdown_extensions:
  - attr_list
  - md_in_html # enable lazy loading images via ![!](assets/test.jpg){ loading=lazy }
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - markdown.extensions.toc:
      baselevel: 1
      permalink: ""
  - toc:
      title: Table of Contents
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: ec-jrc/KCEO-Glossary
      branch: main
      enabled: !ENV [CI, false]
  - tags:
      tags_file: tags.md
  - glightbox
  - blog
  # - social # temporarily disabled as it breaks CI
  - privacy
