import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  glossary: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'concepts',
      label: 'Concepts',
    },
    {
      type: 'doc',
      id: 'contribute',
      label: 'Contribute',
    },
    {
      type: 'category',
      label: 'Terms A–C',
      collapsed: true,
      items: [
        'terms/accuracy',
        'terms/ancillary_data',
        'terms/anthroposphere',
        'terms/archive',
        'terms/area_of_interest',
        'terms/atmosphere',
        'terms/auxiliary_data',
        'terms/backup',
        'terms/band_central_wavelength',
        'terms/baseline',
        'terms/biosphere',
        'terms/business_continuity',
        'terms/calibration',
        'terms/cartographic_projection',
        'terms/catalogue',
        'terms/cell',
        'terms/characteristic',
        'terms/classification_system',
        'terms/classification_system_levels',
        'terms/climate_projection',
        'terms/collection',
        'terms/collection_update',
        'terms/collection_upgrade',
        'terms/confidence_interval',
        'terms/copernicus_service_provider',
        'terms/coverage_interval',
        'terms/cryosphere',
        'terms/custodian',
      ],
    },
    {
      type: 'category',
      label: 'Terms D–F',
      collapsed: true,
      items: [
        'terms/data',
        'terms/data_access',
        'terms/data_format',
        'terms/data_licencing',
        'terms/decommissioned_product',
        'terms/deprecated_product',
        'terms/derivative_product',
        'terms/dispose',
        'terms/duration',
        'terms/dwell_time',
        'terms/earth_observation',
        'terms/earth_observation_based_output',
        'terms/earth_observation_product',
        'terms/earth_spheres',
        'terms/entity',
        'terms/environmental_process',
        'terms/eo_space_data',
        'terms/expanded_uncertainty',
        'terms/feature',
        'terms/final_product_version',
        'terms/forecast_range',
      ],
    },
    {
      type: 'category',
      label: 'Terms G–L',
      collapsed: true,
      items: [
        'terms/geocoding',
        'terms/geographic_coordinate_reference_system',
        'terms/geographic_data',
        'terms/geographic_grid',
        'terms/geographic_identifier',
        'terms/geolocating',
        'terms/geolocation_information',
        'terms/geopositioning',
        'terms/georectifying',
        'terms/geospatial_data',
        'terms/geosphere',
        'terms/granule',
        'terms/grid',
        'terms/hydrosphere',
        'terms/impact',
        'terms/in-situ_observation',
        'terms/information',
        'terms/instrument_data',
        'terms/laboratory_observation',
        'terms/latency',
        'terms/lead_time',
        'terms/lithosphere',
        'terms/location',
        'terms/location_error',
        'terms/long_term_preservation',
      ],
    },
    {
      type: 'category',
      label: 'Terms M–O',
      collapsed: true,
      items: [
        'terms/measurand',
        'terms/measurement',
        'terms/measurement_uncertainty',
        'terms/metadata',
        'terms/minimum_mapping_unit',
        'terms/minimum_mapping_width',
        'terms/model',
        'terms/near_real_time_data',
        'terms/object',
        'terms/observation',
        'terms/obsolete_product_or_collection',
        'terms/outcome',
      ],
    },
    {
      type: 'category',
      label: 'Terms P–R',
      collapsed: true,
      items: [
        'terms/path',
        'terms/period',
        'terms/period_identifier',
        'terms/phenomenon',
        'terms/place',
        'terms/policy',
        'terms/policy_cycle',
        'terms/policy_file',
        'terms/policy_making',
        'terms/policy_milestone',
        'terms/policy_objective',
        'terms/policy_target',
        'terms/position',
        'terms/preservation',
        'terms/process',
        'terms/product',
        'terms/property',
        'terms/provisional_product',
        'terms/quality_indicator',
        'terms/quantity',
        'terms/reference',
        'terms/remote_sensing',
        'terms/replicability',
        'terms/representativeness',
        'terms/reproducibility',
      ],
    },
    {
      type: 'category',
      label: 'Terms S–Z',
      collapsed: true,
      items: [
        'terms/sample',
        'terms/sensor',
        'terms/source_data',
        'terms/spatial_completeness',
        'terms/spatial_consistency',
        'terms/spatial_extent',
        'terms/spatial_reporting_unit',
        'terms/spatial_resolution',
        'terms/spectral_band',
        'terms/spectral_bandwidth',
        'terms/spectral_resolution',
        'terms/stability',
        'terms/standard_uncertainty',
        'terms/steward',
        'terms/temporal_consistency',
        'terms/temporal_extent',
        'terms/temporal_reporting_period',
        'terms/temporal_resolution',
        'terms/temporal_revisit',
        'terms/thematic_resolution',
        'terms/thematic_uncertainty',
        'terms/time_of_day',
        'terms/time_of_year',
        'terms/timeliness',
        'terms/traceability',
        'terms/trait',
        'terms/uncertainty',
        'terms/update_frequency',
        'terms/user',
        'terms/user_interface',
        'terms/validation',
        'terms/value',
        'terms/verification',
        'terms/version_control',
        'terms/vertical_levels',
      ],
    },
    {
      type: 'doc',
      id: 'changelog',
      label: 'Changelog',
    },
    {
      type: 'doc',
      id: 'impressum',
      label: 'Contact',
    },
  ],
};

export default sidebars;
