import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  glossary: [
    { type: 'autogenerated', dirName: 'terms' },
  ],
};

export default sidebars;
