import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  glossary: [
    { type: 'doc', id: 'introduction', label: 'Introduction' },
    { type: 'doc', id: 'concepts', label: 'Concepts' },
    { type: 'doc', id: 'contribute', label: 'Contribute' },
    { type: 'doc', id: 'data-access', label: 'Data Access' },
    { type: 'doc', id: 'changelog', label: 'Changelog' },
    { type: 'doc', id: 'impressum', label: 'Contact' },
    {
      type: 'category',
      label: 'Terms',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'terms' }],
    },

  ],
};

export default sidebars;
