authors:
  dominik:
    name: Dominik Weckmüller
    description: KCEO Team
    avatar: https://avatars.githubusercontent.com/u/47481567?v=4
  meriam:
    name: Meriam Lahsaini
    description: KCEO Team
    avatar: https://dagshub.com/avatars/31302?s=290
  peter:
    name: Peter Strobl
    description: KCEO Team
    avatar: https://media.licdn.com/dms/image/v2/C4E03AQH5b1TGJE-ifg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1517469478365?e=1749081600&v=beta&t=BZDLg_RjW3G3pJ7Ginahjq_UWz9vOarofmxWjIweZr4
