name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write # Needed for mkdocs gh-deploy to push to gh-pages branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Configure Git
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    
      # Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Install uv and set up a virtual environment
      - run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          source $HOME/.cargo/env
          uv venv --python 3.11
          uv pip install "mkdocs-material[imaging]==9.5.18"
          uv pip install mkdocs-glightbox mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2

      # 6. Run pre-build scripts
      - name: Run pre-build script (Remove cross-links)
        run: python scripts/remove_cross_links_in_term_definitions.py

      - name: Run pre-build script (Add cross-links)
        run: python scripts/add_cross_links_in_term_definitions.py

      # Deploy with mkdocs
      - name: Build and deploy MkDocs site
        env:
          # Provide the GITHUB_TOKEN to the git-committers plugin
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
        run: uv run mkdocs gh-deploy --force
